### ISSUE TITLE
search in join table not working

### ISSUE THREAD

**Issue by robiokta** [irsyadulibad/ci4-datatables#8]
when searching on joined table not working properly, only parent table found record,
when table a join with table b, i can't find result on table b,
thanks

**Comment by irsyadulibad** [comment]
Thank you for reporting the problem

I've resolved the issue, problem lies in the skipped query because the field names in the joined table are not registered.
You can update the library by running the command
```
composer update irsyadulibad/codeigniter4-datatables
```
if you not using the composer, you can download the repository and replace all the library files.
